### ISSUE TITLE
Open in existing window after creation

### ISSUE THREAD

**Issue by yeekangc** [MicroShed/mp-starter-vscode-ext#4]
Can we open the generated project in the existing VS Code window instead of a new one?

**Comment by kathrynkodama** [comment]
If the current VS Code workspace is empty we will use the current VS Code window. If there is already a project open in the current workspace we will open the project in a new window.

**Comment by rzgry** [comment]
Addressed with #23. Extension now asks you if you want to open the generated project in a new window or add it to the current workspace.
