### ISSUE TITLE
Delete existing directory if generating into a directory that already exists

### ISSUE THREAD

**Issue by rzgry** [MicroShed/mp-starter-vscode-ext#51]
Projects are generated into a folder using the provided artifact id as the folder name. But if a folder with that name already exists, the contents of the existing folder and the generated microprofile starter project will be merged.

Would be good to display a warning and ~~ask users if they are sure before generating content into an existing folder~~, ask users before deleting the existing folder and replacing it with the generated project.

We should update this message to mention the folder will be deleted instead of merged. And then delete the existing folder. https://github.com/MicroShed/mp-starter-vscode-ext/blob/f8960f9ba2ecfc842b55f512e0bc5db79d00d3df/src/util/vscodePrompts.ts#L165

**Comment by kathrynkodama** [comment]
Instead of merging the existing folder with the generated MicroProfile Starter project, after the user confirms they would like to continue, we should delete the existing folder and generate the MicroProfile Starter project.
