### ISSUE TITLE
Update vscode extension to use MP 1.5 API

### ISSUE THREAD

**Issue by Emily-Jiang** [MicroShed/mp-starter-vscode-ext#74]
MP Starter API v1.5 was just released. Please update vscode extension pack to use the new API. GraphQL is provided in this new API

**Comment by kathrynkodama** [comment]
@Emily-Jiang 
~~https://start.microprofile.io/api/5 does not seem to work - but looks like https://start.microprofile.io/api/4/supportMatrix now includes GraphQL, is that expected?~~

EDIT: Thank you Emily, per the answer on Gitter the API is versioned for compatibility, not new content, so /4/ is expected.

**Comment by kathrynkodama** [comment]
Since the API endpoint has not changed, we do not need to make any updates to the VS Code extension. All works as expected.

**Comment by Emily-Jiang** [comment]
Thank you @kathrynkodama ! Good to know!
